apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: k8s-pihole
  labels:
    app: pihole
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: pihole-env
              key: TZ
        - name: PIHOLE_DNS_
          valueFrom:
            configMapKeyRef:
              name: pihole-env
              key: PIHOLE_DNS_
        - name: WEBPASSWORD
          valueFrom:
            configMapKeyRef:
              name: pihole-env
              key: WEBPASSWORD
        ports:
        - name: web
          containerPort: 80
        - name: dns
          protocol: UDP
          containerPort: 53
        - name: tcpdns
          protocol: TCP
          containerPort: 53
        volumeMounts:
        - name: pihole-adlists
          mountPath: /etc/pihole/adlists.list
          subPath: adlists.list
        - name: pihole-regex
          mountPath: /etc/pihole/regex.list
          subPath: regex.list
        - name: pihole-custom
          mountPath: /etc/pihole/custom.list
          subPath: custom.list
      volumes:
        - name: pihole-adlists
          configMap:
            name: pihole-adlists
        - name: pihole-regex
          configMap: 
            name: pihole-regex
        - name: pihole-custom
          configMap:
            name: pihole-custom
