kind: Service
apiVersion: v1
metadata:
  name: pihole-web-service
  namespace : k8s-pihole
  annotations:
    metallb.universe.tf/address-pool: inside
    metallb.universe.tf/allow-shared-ip: k8s-pihole
spec:
  loadBalancerIP: 192.168.0.192
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name : web
  type: LoadBalancer 
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-service
  namespace: k8s-pihole
  annotations:
    metallb.universe.tf/address-pool: inside
    metallb.universe.tf/allow-shared-ip: k8s-pihole
spec:
  loadBalancerIP: 192.168.0.192
  externalTrafficPolicy: Cluster
  selector:
    app: pihole
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name : dns
  type: LoadBalancer 
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-tcp-dns-service
  namespace: k8s-pihole
  annotations:
    metallb.universe.tf/address-pool: inside
    metallb.universe.tf/allow-shared-ip: k8s-pihole
spec:
  loadBalancerIP: 192.168.0.192
  externalTrafficPolicy: Cluster
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
    name: tcp-dns
  type: LoadBalancer

